AWSTemplateFormatVersion: '2010-09-09'
Description: 'Este template provisiona a infraestrutura de notificações para o sistema FastDelivery Tracker da Hamburgueria, utilizando um tópico AWS SNS central e suas respectivas permissões.'

# =====================================================================================
# Parâmetros
# Define valores de entrada para customizar a implantação da stack.
# =====================================================================================
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, hom, main]
    Description: 'Especifica o ambiente (ex: dev, hom, main) onde a stack será implantada. Usado para aplicar tags aos recursos, facilitando a identificação e o gerenciamento.'

# =====================================================================================
# Recursos
# Define os recursos AWS que serão criados e gerenciados por esta stack.
# =====================================================================================
Resources:
  # --- Tópico SNS ---
  # Tópico SNS central para o sistema FastDelivery.
  # Este tópico atua como um hub de mensagens para eventos importantes, como 'pedido recebido',
  # 'pedido em preparo', 'entregador a caminho', etc.
  # O nome 'FastDeliveryTopic' é fixo, conforme requisito, para garantir que outros serviços
  # possam publicar mensagens nele de forma consistente e desacoplada.
  FastDeliveryTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: FastDeliveryTopic
      DisplayName: FastDelivery Notifications - Hamburgueria
      Tags:
        - Key: Project
          Value: FastDeliveryTracker
        - Key: Environment
          Value: !Ref Environment

  # --- Inscrição (Subscription) para a Lambda ---
  # Conecta o tópico SNS à função Lambda 'NotifyOwnerLambda'.
  # Qualquer mensagem publicada no 'FastDeliveryTopic' será automaticamente encaminhada
  # para esta função para processamento (ex: notificar o dono da hamburgueria).
  # NOTA: A função Lambda 'NotifyOwnerLambda' não é criada neste template. Ela deve ser
  # definida em outro lugar na mesma stack ou seu ARN deve ser importado.
  NotifyOwnerSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn: !Ref FastDeliveryTopic
      Endpoint: !GetAtt NotifyOwnerLambda.Arn

  # --- Permissão para a Lambda ---
  # Permissão baseada em recurso (Resource-Based Policy) para a função Lambda.
  # Esta política concede explicitamente ao serviço SNS (sns.amazonaws.com) a autorização
  # para invocar a função 'NotifyOwnerLambda' sempre que uma mensagem for publicada no tópico
  # especificado em 'SourceArn'. Sem isso, o SNS não teria permissão para acionar a Lambda.
  NotifyOwnerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref NotifyOwnerLambda
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref FastDeliveryTopic

# =====================================================================================
# Outputs
# Expõe informações importantes sobre os recursos criados para serem usadas por
# outras stacks, scripts ou para consulta no console da AWS.
# =====================================================================================
Outputs:
  SnsTopicArn:
    Description: 'ARN (Amazon Resource Name) completo do tópico SNS. Essencial para referenciar este tópico em outras stacks ou serviços.'
    Value: !Ref FastDeliveryTopic
    Export:
      Name: !Sub ${AWS::StackName}-SnsTopicArn

  SnsTopicName:
    Description: 'Nome físico do tópico SNS. Exportado para conveniência de referência.'
    Value: FastDeliveryTopic # O nome é fixo, então podemos usar o valor literal.
    Export:
      Name: !Sub ${AWS::StackName}-SnsTopicName