AWSTemplateFormatVersion: '2010-09-09'
Description: 'Este template provisiona a infraestrutura de notificações para o sistema FastDelivery Tracker da Hamburgueria, utilizando um tópico AWS SNS central e suas respectivas permissões.'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, hom, main]
    Description: 'Especifica o ambiente (ex: dev, hom, main) onde a stack será implantada.'
  OrdersQueueArn:
    Type: String
    Description: 'ARN da fila SQS de pedidos'

Resources:
  FastDeliveryTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: FastDeliveryTopic
      DisplayName: FastDelivery Notifications - Hamburgueria
      Tags:
        - Key: Project
          Value: FastDeliveryTracker
        - Key: Environment
          Value: !Ref Environment

  SNSToSqsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      Endpoint: !Ref OrdersQueueArn
      TopicArn: !Ref FastDeliveryTopic
      RawMessageDelivery: 'true'

Outputs:
  SnsTopicArn:
    Description: 'ARN (Amazon Resource Name) completo do tópico SNS.'
    Value: !Ref FastDeliveryTopic
    Export:
      Name: !Sub ${AWS::StackName}-SnsTopicArn'